"""phase9_ai_provider_management

Revision ID: 268a41294965
Revises: f76fc6eccc76
Create Date: 2024-01-15 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268a41294965'
down_revision: Union[str, None] = 'f76fc6eccc76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Phase 9 AI Provider Management."""
    
    # Create provider_type enum
    provider_type_enum = sa.Enum('text', 'image', 'video', 'voice', 'research', name='providertype')
    provider_type_enum.create(op.get_bind())
    
    # ### commands auto generated by Alembic - please adjust! ###
    # AI Providers table
    op.create_table('ai_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', provider_type_enum, nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_org_type', 'ai_providers', ['organization_id', 'provider_type'])
    op.create_index('idx_provider_active', 'ai_providers', ['is_active'])
    op.create_index('idx_provider_type', 'ai_providers', ['provider_type'])
    
    # AI Profiles table
    op.create_table('ai_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('text_provider_id', sa.Integer(), nullable=True),
    sa.Column('image_provider_id', sa.Integer(), nullable=True),
    sa.Column('video_provider_id', sa.Integer(), nullable=True),
    sa.Column('voice_provider_id', sa.Integer(), nullable=True),
    sa.Column('research_provider_id', sa.Integer(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True, default=False),
    sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voice_provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['research_provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profile_org', 'ai_profiles', ['organization_id'])
    op.create_index('idx_profile_default', 'ai_profiles', ['is_default'])
    
    # AI Usage Records table
    op.create_table('ai_usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.BigInteger(), nullable=True, default=0),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True, default=0),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True, default=0),
    sa.Column('cost_usd', sa.Float(), nullable=True, default=0.0),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True, default=0),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('response_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['ai_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_org_created', 'ai_usage_records', ['organization_id', 'created_at'])
    op.create_index('idx_usage_cost', 'ai_usage_records', ['cost_usd'])
    op.create_index('idx_usage_profile', 'ai_usage_records', ['profile_id'])
    op.create_index('idx_usage_provider', 'ai_usage_records', ['provider_id'])
    
    # Add updated_at trigger equivalent for ai_providers
    # Note: SQLAlchemy onupdate doesn't translate to DDL, handled at ORM level
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - Phase 9 AI Provider Management."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_usage_provider', table_name='ai_usage_records')
    op.drop_index('idx_usage_profile', table_name='ai_usage_records')
    op.drop_index('idx_usage_cost', table_name='ai_usage_records')
    op.drop_index('idx_usage_org_created', table_name='ai_usage_records')
    op.drop_table('ai_usage_records')
    
    op.drop_index('idx_profile_default', table_name='ai_profiles')
    op.drop_index('idx_profile_org', table_name='ai_profiles')
    op.drop_table('ai_profiles')
    
    op.drop_index('idx_provider_type', table_name='ai_providers')
    op.drop_index('idx_provider_active', table_name='ai_providers')
    op.drop_index('idx_provider_org_type', table_name='ai_providers')
    op.drop_table('ai_providers')
    
    # Drop enum
    provider_type_enum = sa.Enum('text', 'image', 'video', 'voice', 'research', name='providertype')
    provider_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
