"""initial_complete_schema

Revision ID: f76fc6eccc76
Revises: 
Create Date: 2026-07-22 08:06:02.458973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76fc6eccc76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('max_teams', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_channels', sa.Integer(), nullable=True),
    sa.Column('storage_limit_gb', sa.Float(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index('idx_org_created', ['created_at'], unique=False)
        batch_op.create_index('idx_org_slug', ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_slug'), ['slug'], unique=True)

    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_role_org_slug')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('idx_role_org', ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_organization_id'), ['organization_id'], unique=False)

    op.create_table('teams',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_team_org_slug')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index('idx_team_org', ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('external_auth_id', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_user_org_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_org', ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_external_auth_id'), ['external_auth_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_created', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_resource', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('channel_profiles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('audience_definition', sa.Text(), nullable=True),
    sa.Column('age_range_min', sa.Integer(), nullable=True),
    sa.Column('age_range_max', sa.Integer(), nullable=True),
    sa.Column('gender_focus', sa.String(length=50), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('content_style', sa.String(length=255), nullable=True),
    sa.Column('tone', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('visual_identity', sa.JSON(), nullable=True),
    sa.Column('image_dimensions', sa.String(length=20), nullable=True),
    sa.Column('video_format', sa.String(length=20), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=True),
    sa.Column('voice_type', sa.String(length=100), nullable=True),
    sa.Column('character_avatar', sa.JSON(), nullable=True),
    sa.Column('branding_rules', sa.JSON(), nullable=True),
    sa.Column('forbidden_elements', sa.JSON(), nullable=True),
    sa.Column('recurring_characters', sa.JSON(), nullable=True),
    sa.Column('hashtag_strategy', sa.JSON(), nullable=True),
    sa.Column('seo_rules', sa.JSON(), nullable=True),
    sa.Column('storytelling_rules', sa.Text(), nullable=True),
    sa.Column('music_style', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_profiles', schema=None) as batch_op:
        batch_op.create_index('idx_channel_org', ['organization_id'], unique=False)
        batch_op.create_index('idx_channel_platform', ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_profiles_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_profiles_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_profiles_team_id'), ['team_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index('idx_role_permission', ['role_id', 'permission_id'], unique=False)

    op.create_table('team_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role_override', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index('idx_team_member_team', ['team_id'], unique=False)
        batch_op.create_index('idx_team_member_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('custom_permissions', sa.JSON(), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'role_id', name='uq_user_role_org')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index('idx_user_role_role', ['role_id'], unique=False)
        batch_op.create_index('idx_user_role_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('content_strategies',
    sa.Column('channel_profile_id', sa.Integer(), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('content_pillars', sa.JSON(), nullable=True),
    sa.Column('publishing_schedule', sa.JSON(), nullable=True),
    sa.Column('posting_frequency', sa.String(length=50), nullable=True),
    sa.Column('target_posts_per_month', sa.Integer(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('cross_platform_strategy', sa.Text(), nullable=True),
    sa.Column('kpis', sa.JSON(), nullable=True),
    sa.Column('target_metrics', sa.JSON(), nullable=True),
    sa.Column('content_calendar', sa.JSON(), nullable=True),
    sa.Column('seasonal_campaigns', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_profile_id'], ['channel_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_strategies', schema=None) as batch_op:
        batch_op.create_index('idx_strategy_channel', ['channel_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_strategies_channel_profile_id'), ['channel_profile_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_content_strategies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_strategies_organization_id'), ['organization_id'], unique=False)

    op.create_table('production_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('channel_profile_id', sa.Integer(), nullable=False),
    sa.Column('narrator_character', sa.JSON(), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('voice_settings', sa.JSON(), nullable=True),
    sa.Column('visual_style', sa.String(length=255), nullable=True),
    sa.Column('visual_style_prompt', sa.Text(), nullable=True),
    sa.Column('color_palette', sa.JSON(), nullable=True),
    sa.Column('intro_template', sa.Text(), nullable=True),
    sa.Column('outro_template', sa.Text(), nullable=True),
    sa.Column('segment_structure', sa.JSON(), nullable=True),
    sa.Column('duration_target', sa.String(length=50), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('video_format', sa.String(length=20), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('music_style', sa.String(length=255), nullable=True),
    sa.Column('background_music_id', sa.String(length=100), nullable=True),
    sa.Column('sound_effects', sa.JSON(), nullable=True),
    sa.Column('logo_placement', sa.JSON(), nullable=True),
    sa.Column('watermark_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('model_settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_profile_id'], ['channel_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_templates', schema=None) as batch_op:
        batch_op.create_index('idx_template_channel', ['channel_profile_id'], unique=False)
        batch_op.create_index('idx_template_default', ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_templates_channel_profile_id'), ['channel_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_templates_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_templates_organization_id'), ['organization_id'], unique=False)

    op.create_table('playlists',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('playlist_type', sa.Enum('PLANNED_PLAYLIST', 'DYNAMIC_PLAYLIST', name='playlisttype'), nullable=False),
    sa.Column('channel_profile_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('source_urls', sa.JSON(), nullable=True),
    sa.Column('monitoring_keywords', sa.JSON(), nullable=True),
    sa.Column('auto_generate', sa.Boolean(), nullable=True),
    sa.Column('episode_roadmap', sa.JSON(), nullable=True),
    sa.Column('total_planned_episodes', sa.Integer(), nullable=True),
    sa.Column('production_template_id', sa.Integer(), nullable=True),
    sa.Column('default_character', sa.String(length=255), nullable=True),
    sa.Column('default_style', sa.String(length=255), nullable=True),
    sa.Column('default_duration', sa.String(length=50), nullable=True),
    sa.Column('default_format', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_profile_id'], ['channel_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_template_id'], ['production_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.create_index('idx_playlist_channel', ['channel_profile_id'], unique=False)
        batch_op.create_index('idx_playlist_type', ['playlist_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlists_channel_profile_id'), ['channel_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlists_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlists_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlists_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlists_playlist_type'), ['playlist_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlists_title'), ['title'], unique=False)

    op.create_table('episodes',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'RESEARCHING', 'SCRIPT_READY', 'PRODUCING', 'REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='episodestatus'), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('channel_profile_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('production_template_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('research_data', sa.JSON(), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('storyboard', sa.JSON(), nullable=True),
    sa.Column('thumbnail_id', sa.Integer(), nullable=True),
    sa.Column('seo_data', sa.JSON(), nullable=True),
    sa.Column('publish_metadata', sa.JSON(), nullable=True),
    sa.Column('published_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['channel_profile_id'], ['channel_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_template_id'], ['production_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index('idx_episode_playlist', ['playlist_id'], unique=False)
        batch_op.create_index('idx_episode_scheduled', ['scheduled_for'], unique=False)
        batch_op.create_index('idx_episode_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_channel_profile_id'), ['channel_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_playlist_id'), ['playlist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_title'), ['title'], unique=False)

    op.create_table('assets',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'SUBTITLE', 'SCRIPT', 'THUMBNAIL', 'DOCUMENT', 'OTHER', name='assettype'), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('storage_provider', sa.String(length=50), nullable=True),
    sa.Column('storage_bucket', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('storage_url', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.String(length=20), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('processing_metadata', sa.JSON(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index('idx_asset_episode', ['episode_id'], unique=False)
        batch_op.create_index('idx_asset_storage', ['storage_provider', 'storage_bucket'], unique=False)
        batch_op.create_index('idx_asset_type', ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_organization_id'), ['organization_id'], unique=False)

    op.create_table('content_jobs',
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'RETRYING', name='contentjobstatus'), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('production_template_id', sa.Integer(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_template_id'], ['production_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_job_agent', ['agent_name'], unique=False)
        batch_op.create_index('idx_job_created', ['created_at'], unique=False)
        batch_op.create_index('idx_job_episode', ['episode_id'], unique=False)
        batch_op.create_index('idx_job_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_jobs_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_jobs_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_jobs_status'), ['status'], unique=False)

    op.create_table('agent_executions',
    sa.Column('execution_id', sa.String(length=100), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'TIMEOUT', name='agentexecutionstatus'), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('content_job_id', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_stack_trace', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=True),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('parent_execution_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_job_id'], ['content_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.create_index('idx_agent_created', ['created_at'], unique=False)
        batch_op.create_index('idx_agent_episode', ['episode_id'], unique=False)
        batch_op.create_index('idx_agent_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_executions_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_executions_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_executions_execution_id'), ['execution_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_executions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_executions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_executions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_executions_status'))
        batch_op.drop_index(batch_op.f('ix_agent_executions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_agent_executions_id'))
        batch_op.drop_index(batch_op.f('ix_agent_executions_execution_id'))
        batch_op.drop_index(batch_op.f('ix_agent_executions_episode_id'))
        batch_op.drop_index(batch_op.f('ix_agent_executions_agent_name'))
        batch_op.drop_index('idx_agent_status')
        batch_op.drop_index('idx_agent_episode')
        batch_op.drop_index('idx_agent_created')

    op.drop_table('agent_executions')
    with op.batch_alter_table('content_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_content_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_content_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_content_jobs_episode_id'))
        batch_op.drop_index(batch_op.f('ix_content_jobs_agent_name'))
        batch_op.drop_index('idx_job_status')
        batch_op.drop_index('idx_job_episode')
        batch_op.drop_index('idx_job_created')
        batch_op.drop_index('idx_job_agent')

    op.drop_table('content_jobs')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_organization_id'))
        batch_op.drop_index(batch_op.f('ix_assets_id'))
        batch_op.drop_index(batch_op.f('ix_assets_episode_id'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_type'))
        batch_op.drop_index('idx_asset_type')
        batch_op.drop_index('idx_asset_storage')
        batch_op.drop_index('idx_asset_episode')

    op.drop_table('assets')
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodes_title'))
        batch_op.drop_index(batch_op.f('ix_episodes_status'))
        batch_op.drop_index(batch_op.f('ix_episodes_playlist_id'))
        batch_op.drop_index(batch_op.f('ix_episodes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_episodes_id'))
        batch_op.drop_index(batch_op.f('ix_episodes_creator_id'))
        batch_op.drop_index(batch_op.f('ix_episodes_channel_profile_id'))
        batch_op.drop_index('idx_episode_status')
        batch_op.drop_index('idx_episode_scheduled')
        batch_op.drop_index('idx_episode_playlist')

    op.drop_table('episodes')
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlists_title'))
        batch_op.drop_index(batch_op.f('ix_playlists_playlist_type'))
        batch_op.drop_index(batch_op.f('ix_playlists_organization_id'))
        batch_op.drop_index(batch_op.f('ix_playlists_id'))
        batch_op.drop_index(batch_op.f('ix_playlists_creator_id'))
        batch_op.drop_index(batch_op.f('ix_playlists_channel_profile_id'))
        batch_op.drop_index('idx_playlist_type')
        batch_op.drop_index('idx_playlist_channel')

    op.drop_table('playlists')
    with op.batch_alter_table('production_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_templates_organization_id'))
        batch_op.drop_index(batch_op.f('ix_production_templates_name'))
        batch_op.drop_index(batch_op.f('ix_production_templates_id'))
        batch_op.drop_index(batch_op.f('ix_production_templates_channel_profile_id'))
        batch_op.drop_index('idx_template_default')
        batch_op.drop_index('idx_template_channel')

    op.drop_table('production_templates')
    with op.batch_alter_table('content_strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_strategies_organization_id'))
        batch_op.drop_index(batch_op.f('ix_content_strategies_id'))
        batch_op.drop_index(batch_op.f('ix_content_strategies_channel_profile_id'))
        batch_op.drop_index('idx_strategy_channel')

    op.drop_table('content_strategies')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_organization_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_id'))
        batch_op.drop_index('idx_user_role_user')
        batch_op.drop_index('idx_user_role_role')

    op.drop_table('user_roles')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_organization_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_id'))
        batch_op.drop_index('idx_team_member_user')
        batch_op.drop_index('idx_team_member_team')

    op.drop_table('team_members')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_role_permission')

    op.drop_table('role_permissions')
    with op.batch_alter_table('channel_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_profiles_team_id'))
        batch_op.drop_index(batch_op.f('ix_channel_profiles_organization_id'))
        batch_op.drop_index(batch_op.f('ix_channel_profiles_name'))
        batch_op.drop_index(batch_op.f('ix_channel_profiles_id'))
        batch_op.drop_index('idx_channel_platform')
        batch_op.drop_index('idx_channel_org')

    op.drop_table('channel_profiles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('idx_audit_resource')
        batch_op.drop_index('idx_audit_created')
        batch_op.drop_index('idx_audit_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_external_auth_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_user_org')
        batch_op.drop_index('idx_user_email')

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_organization_id'))
        batch_op.drop_index(batch_op.f('ix_teams_id'))
        batch_op.drop_index('idx_team_org')

    op.drop_table('teams')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_organization_id'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))
        batch_op.drop_index('idx_role_org')

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_slug'))
        batch_op.drop_index(batch_op.f('ix_permissions_id'))

    op.drop_table('permissions')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))
        batch_op.drop_index('idx_org_slug')
        batch_op.drop_index('idx_org_created')

    op.drop_table('organizations')
    # ### end Alembic commands ###
